### PR TITLE
Continuous query fixes

### PR DESCRIPTION
**Pull request by vjuranek**
this is backport of https://github.com/radargun/radargun/pull/318

* avoid ISPN8 dependency in JDG6
* fix continues query after few classes were rename in ISPN

### CODE REVIEW

**Comment by vjuranek** [comment]
PR updates. Exception seen by @jmarkos is not present any more, but when running with scenarios provided by @jmarkos , it still fails with following exception:
```
java.lang.RuntimeException: java.lang.NullPointerException
        at org.radargun.service.InfinispanLifecycle.start(InfinispanLifecycle.java:61)
        at org.radargun.service.InfinispanKillableLifecycle.start(InfinispanKillableLifecycle.java:51)
        at org.radargun.stages.lifecycle.LifecycleHelper.start(LifecycleHelper.java:59)
        at org.radargun.stages.lifecycle.ServiceStartStage.executeOnSlave(ServiceStartStage.java:86)
        at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:90)
        at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158)
Caused by: java.lang.NullPointerException
        at org.radargun.service.Infinispan51EmbeddedService.createCacheManager(Infinispan51EmbeddedService.java:139)
        at org.radargun.service.InfinispanEmbeddedService.startCaches(InfinispanEmbeddedService.java:116)
        at org.radargun.service.Infinispan51EmbeddedService.startCaches(Infinispan51EmbeddedService.java:100)
        at org.radargun.service.InfinispanLifecycle.start(InfinispanLifecycle.java:45)
        ... 5 more
```
IMHO this it not related to continuous query, maybe some issue in scenario?

**Comment by vjuranek** [comment]
My bad, I didn't noticed ISPN config file is missing. Now everything seems to work fine.

**Comment by mcimbora** [comment]
@vjuranek Could you please fix the indentation (4 -> 3 spaces by default) - JDG66HotrodService, JDG66HotrodQueryable, JDGHotrodContinuousQuery. There's a checkstyle failure.

**Comment by vjuranek** [comment]
@mcimbora PR update, now ` mvn checkstyle:check -Pjdg` is passing (I guess I forgot to run it with `-Pjdg` before submitting original PR - sorry)

**Comment by rvansa** [comment]
I'll merge this, but please create (and follow) and issue to make the trait state-less.

**Comment by vjuranek** [comment]
@rvansa  thanks - done in #363

**Comment by rvansa** [comment]
@vjuranek Hey, seems you forgot to set the service versions in plugin.properties

**Comment by vjuranek** [comment]
@rvansa uf, in which plugin, `jdg66`?

**Comment by rvansa** [comment]
@vjuranek infinispan81 and 82

**Comment by vjuranek** [comment]
@rvansa ops, thanks for spotting it - should be fixed in PR #364, resp. PR #365 for `branch_2.x`

**Pull request merged**
