### PR TITLE
JGroups probe wrapper

### PR DESCRIPTION
**Pull request by mcimbora**
* Enable JGroups tuning via probe. Just a preview, may implement additional features (e.g. scheduling specified query task - similar to JGroupsDumper, but more general).
* Added custom infinispan configuration, as enable_diagnostics property of TP needs to be enabled

### CODE REVIEW

**Comment by alanfx** [comment]
@mcimbora it seems like this stage could apply to both the infinispan and jgroups plugins, so it makes sense to me to have it as a stage. Does that make sense to you, @rvansa?

**Comment by rvansa** [comment]
Generally, I find having a stage specific to JGroups a bit confusing, but I guess it makes sense here. So be it.

However, rather than another JGroups config, I would welcome service parameter that would set the `enable_diagnostics` programmatically.

Do we want to have this still as a preview? It's been around for a few months.

**Comment by alanfx** [comment]
I agree that this would be more useful if it did not have a separate configuration and just programmatically changed the `enable_diagnostics` property.

**Comment by mcimbora** [comment]
@alanfx @rvansa Makes sense, fixed.

**Comment by rvansa** [comment]
I think that in pre-7.0 versions, the enableDiagnostics property should not be at all, rather than check configuration and throw exception. That gives it rather confusing meaning - documentation for 5.1 says what happens in future versions until 7.0, and 7.0 is not in the property description at all.

I would just put it into 7.0 and further. Do you have different opinion, @alanfx ?

**Comment by alanfx** [comment]
Hey @rvansa I think that probe will still work in pre-7.0 versions. The difference is that in versions >= 7.0 `enable_diagnostics` can be enabled programmatically. In earlier versions `enable_diagnostics` has to be set to `true` in the configuration.

**Comment by rvansa** [comment]
@alanfx Nobody prohibits you from using the probe for pre-7.0, the `enable_diagnostics` does not need to be there to let you use the probe.

**Comment by alanfx** [comment]
@rvansa ok, then I am confused! If probe can be used when `enable_diagnostics` is `false`, then we don't need the code to enable it programmatically either. The JGroups documentation implies that `enable_diagnostics` needs to be set to `true`. @mcimbora?

**Comment by rvansa** [comment]
@alanfx Sorry about the confusion - probe can be used if `InfinispanXXService.enable_diagnostics` is not set, but `TP.enable_diagnostics` is set to true. The programmatic change in Service is useful in order to reduce number of JGroups configurations. For older versions you need the configuration with this enabled anyway. So the only value is early failure when benchmarks (explicitly) expects the configuration to be have this enabled, and I think that the loss of elegance is not worth it (as user specifies the configurations in benchmark anyway).

**Comment by alanfx** [comment]
IMO failing to start the service if `TP.enable_diagnostics` is `false` is worthwhile. However, it is true that the probe stage will work even if `InfinispanXXService.enable_diagnostics` isn't set and `TP.enable_diagnostics` is set. Ideally the check could be made directly in the stage, but it doesn't have access to the CacheManager or the JGroupsTransport to retrieve the value of `TP.enable_diagnostics`. I'm not sure what's the best solution here...

**Comment by mcimbora** [comment]
What about just letting the user run the stage even without diagnostics enabled? This way the stage will fail after a timeout, which is a valid result. It's user's responsibility to set up the JGroups configuration in a correct way.

**Comment by alanfx** [comment]
IMO the current implementation of this PR best possible at this point. The implementation isn't perfect, but if the benchmark file is written "correctly" and includes the `InfinispanXXService.enable_diagnostics` then there is a benefit over just failing by timing out in the stage.

**Comment by rvansa** [comment]
If you want to keep the attribute in 5.1 (why not even 4.0?), I would suggest to change the docs to a simpler version, just 'Opens JGroups diagnostics port', and in the old version throw exception that it was not possible. Let's not bother users of new versions with any trickery about versions.

**Comment by mcimbora** [comment]
@rvansa Updated. TP.enable_diagnostics property configurable from infinispan70 onwards (removed from previous plugin versions as it made little sense to keep it there - the field wasn't configurable on TP level).

**Comment by rvansa** [comment]
Integrated, thanks.

**Pull request closed without merging**
