### PR TITLE
Add infinispan90 plugin

### PR DESCRIPTION
**Pull request by jmarkos**
Fixed the CQ support and also modified the example benchmark. I lowered the amount of requests, but it still sometimes fails with
ERROR [org.radargun.stages.test.RunningTest] (Stressor-5) Creating new thread during steady-state!
but that shouldn't be related to this PR.

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @jmarkos, I am getting the following compilation error with this code:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/afield/Development/projects/radargun-master/plugins/infinispan90/src/main/java/org/radargun/service/Infinispan90HotrodService.java:[14,27] createContinuousQuery() in org.radargun.service.Infinispan90HotrodService cannot override createContinuousQuery() in org.radargun.service.Infinispan80HotrodService
  return type org.radargun.traits.ContinuousQuery is not compatible with org.radargun.service.InfinispanHotrodContinuousQuery
```

I *think* that `Infinispan90HotrodContinuousQuery` needs to extend `InfinispanHotrodContinuousQuery`, but from looking at the classes, I can't tell what is different in Infinispan 9 versus 8. If you still need those new classes, then you should put your name as the author as well!

**Comment by rvansa** [comment]
Wrt author: I think we should remove the author tags completely (in another PR), it's just a pre-git nuisance.

**Comment by jmarkos** [comment]
@alanfx it compiles fine for me with 
mvn clean install -Dno-chm -Dno-ehcache -Dno-jbosscache -Dno-zip -DskipTests -Dlog4j2 -Pjdg
What command do you use for building?
The new class is needed because of some small changes in infinispan api.

**Comment by alanfx** [comment]
@jmarkos I get the same error with your command. I am using `mvn clean install -DskipTests -Dmaven.test.skip.exec=true -U`. I'll look at it some more.

**Comment by alanfx** [comment]
The problem is that `Infinispan90HotrodService` extends `Infinispan81HotrodService`, but `Infinispan90HotrodContinuousQuery` does not extend `InfinispanHotrodContinuousQuery` and the return type from `Infinispan90HotrodService.createContinuousQuery` is incompatible with `Infinispan81HotrodService.createContinuousQuery`. I can see the differences now in the `Infinispan90HotrodContinuousQuery.Listener` and `Infinispan90HotrodContinuousQuery.createContinuousQuery` code now. You can see my changes to make this compile here: https://github.com/alanfx/radargun/commit/15d448810ba87fb66277ed22129f8479f0a4c6e5

**Comment by alanfx** [comment]
Integrated. Thanks, @jmarkos!

**Pull request closed without merging**
