### PR TITLE
Changed isolation of plugins from class-loading to restarting JVMs

### PR DESCRIPTION
**Pull request by rvansa**
+ couple of further fixes and improvements before bringing in Hibernate benchmarks

### CODE REVIEW

**Comment by alanfx** [comment]
@rvansa this looks good, but I need to test it more. I think this is a big change, but it seems to simplify a lot of things. Just looking for some more examples to make it more clear how to use all of this!

**Comment by mcimbora** [comment]
@rvansa Good job! I'll definitely need some hands-on experience on this, but the code looks fine :-)

**Comment by rvansa** [comment]
@mcimbora @alanfx Addressed all comments, sorry for taking so long!

**Comment by alanfx** [comment]
This version of the PR is blowing up immediately when I try to run any benchmark. The slaves array in RemoteSlaveConnection has three null values and throws a NPE in the mcastBuffer method at line 166. The "if (slaveIndex < 0) {" condition is executed in connectSlaves which does not populate the slaves array until the "} else if (slaves[slaveIndex] == null) {" condition.

Here's the stacktrace:

```
14:52:17,322 INFO  [org.radargun.LaunchMaster] (main) Running in directory: /home/afield/Development/projects/radargun-PR/target/distribution/RadarGun-2.1.0-SNAPSHOT/.
14:52:17,325 INFO  [org.radargun.LaunchMaster] (main) Configuration file is: conf/benchmark-dist.xml
14:52:17,817 INFO  [org.radargun.RemoteSlaveConnection] (main) Master started and listening for connection on: /127.0.0.1:2103
14:52:17,817 INFO  [org.radargun.RemoteSlaveConnection] (main) Waiting 5 seconds for server socket to open completely
14:53:24,821 INFO  [org.radargun.RemoteSlaveConnection] (main) Awaiting registration from 3 slaves.
14:53:31,628 INFO  [org.radargun.RemoteSlaveConnection] (main) Awaiting registration from 2 slaves.
15:03:26,251 INFO  [org.radargun.RemoteSlaveConnection] (main) Awaiting registration from 1 slaves.
15:03:26,251 INFO  [org.radargun.RemoteSlaveConnection] (main) Connection established from 3 slaves.
15:03:26,276 INFO  [org.radargun.Master] (main) Started benchmarking configuration 'Infinispan 5.2 - distributed'
15:03:26,276 INFO  [org.radargun.Master] (main) Starting scenario on Cluster[default=2]
15:03:27,928 ERROR [org.radargun.Master] (main) Exception in Master.run: 
java.lang.NullPointerException
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:58)
	at org.radargun.RemoteSlaveConnection.mcastBuffer(RemoteSlaveConnection.java:166)
	at org.radargun.RemoteSlaveConnection.mcastObject(RemoteSlaveConnection.java:176)
	at org.radargun.RemoteSlaveConnection.sendCluster(RemoteSlaveConnection.java:153)
	at org.radargun.Master.run(Master.java:71)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
15:03:28,659 WARN  [org.radargun.RemoteSlaveConnection] (main) Failed to send termination to slaves.
java.lang.NullPointerException
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:58)
	at org.radargun.RemoteSlaveConnection.mcastBuffer(RemoteSlaveConnection.java:166)
	at org.radargun.RemoteSlaveConnection.mcastObject(RemoteSlaveConnection.java:176)
	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:301)
	at org.radargun.Master.run(Master.java:132)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
15:03:28,660 WARN  [org.radargun.RemoteSlaveConnection] (main) Error closing channel
java.lang.NullPointerException
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:58)
	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:318)
	at org.radargun.Master.run(Master.java:132)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
15:03:28,660 WARN  [org.radargun.RemoteSlaveConnection] (main) Error closing channel
java.lang.NullPointerException
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:58)
	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:318)
	at org.radargun.Master.run(Master.java:132)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
15:03:28,660 WARN  [org.radargun.RemoteSlaveConnection] (main) Error closing channel
java.lang.NullPointerException
	at org.radargun.RemoteSlaveConnection$SlaveRecord.access$100(RemoteSlaveConnection.java:58)
	at org.radargun.RemoteSlaveConnection.release(RemoteSlaveConnection.java:318)
	at org.radargun.Master.run(Master.java:132)
	at org.radargun.LaunchMaster.main(LaunchMaster.java:32)
15:03:28,662 INFO  [org.radargun.ShutDownHook] (Thread-0) Master process is being shutdown
```

**Comment by rvansa** [comment]
Ah, my mistake - seems that running more slaves than is the max size of cluster leads to these errors. I'll fix that asap.

**Comment by rvansa** [comment]
@mcimbora I've rebased the PR, could you review & merge?

**Comment by mcimbora** [comment]
@rvansa Sure, let me see.

**Comment by mcimbora** [comment]
@rvansa Done. Any tests are appreciated.

**Comment by rvansa** [comment]
@mcimbora I've added test for Init/Destroy. I was considering test for XmlConverter, but this would be rather cumbersome to implement, therefore configuration testing should be based on example configurations (verified through bin/test.sh).

**Comment by mcimbora** [comment]
@rvansa Fair enough, integrating. Thanks.

**Pull request closed without merging**
