### PR TITLE
Provide option -Dpackage-latest for packaging only latest version of …

### PR DESCRIPTION
**Pull request by mgencur**
…all plugins

The question is: Do we want to make it default to package only latest versions of plugins?

### CODE REVIEW

**Comment by jmarkos** [comment]
I vote for it being the default, I don't remember the last time I ran something else than the latest version of any plugin.

**Comment by rvansa** [comment]
@jmarkos If that's a default, how will a new user get to know that there's this option and he can switch it off?

If this is a default, please make sure that all the example configs that compare two versions are working on default build. As a rule of thumb, I made all plugins that have publicly available dependencies be compiled by default, to prevent such issues.

**Comment by jmarkos** [comment]
You're right, let's not make it a default then.

**Comment by jmarkos** [comment]
Merged, thanks.

**Pull request closed without merging**
