### PR TITLE
Several small fixes

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by mcimbora** [comment]
I'm hitting build failure https://gist.github.com/mcimbora/3452af32445800b32d2fbcd62281ef30

**Comment by mcimbora** [comment]
@alanfx

**Comment by mcimbora** [comment]
The issue is caused by missing property <plugins.jdg70/> in root pom.xml

**Comment by alanfx** [comment]
Ugh, sorry @mcimbora. I fixed it locally and thought I had pushed it. I will do that now

**Comment by mcimbora** [comment]
@alanfx Integrated, thanks

**Pull request closed without merging**
