### PR TITLE
Initial background package refactoring

### PR DESCRIPTION
**Pull request by mcimbora**
This is an initial proposal of bg package refactoring in order to improve code readibility. What has been done so far:
* Unified LogCheckerPool object hierarchy into a single class - IMO with current implementation, splitting it into separate classes had no benefits. Refactored into a separate class rather than keeping it in LogChecker.
* The same story for StressorRecord - Introduced a separate class merging the whole hierarchy.

Another ideas I'll be working on (TODO):
* Simplify BackgroundOpsManager - at least splitting statistics into separate mngr
* Tracking missing operations & notifications should be performed in a separate object - currently a pool holds the references that breaks class cohesion. Its purpose should be solely to provide a value on demand.
* ?

Should you have any other ideas or comments, feel free to add those.

### CODE REVIEW

**Comment by rvansa** [comment]
So, is this PR already field-tested?

**Comment by mcimbora** [comment]
@rvansa Yes, I've used build with this changes successfully over the past few weeks.

**Comment by mcimbora** [comment]
@rvansa Haha, or did you mean @alanfx-tested?

**Comment by rvansa** [comment]
Nope, but it came to my mind, too :-) Anyway, I've reviewed the PR, if someone gets to integrating it before me, be it so.

**Comment by alanfx** [comment]
It would have to be Field-tested, but no I haven't!

**Comment by alanfx** [comment]
Integrated. Thanks, @mcimbora!

**Pull request closed without merging**
