### PR TITLE
Updating Hazelcast plugin and adding Hazelcast near cache support

### PR DESCRIPTION
**Pull request by gustavolira**
* Updating Hazelcast with latest version
* Adding near cache support on Hazelcast

### CODE REVIEW

**Comment by diegolovison** [comment]
I was doing the initial review and saw changes related to Redis.
Just curious why,

**Comment by gustavolira** [comment]
> I was doing the initial review and saw changes related to Redis.
> Just curious why,
Alan asked me to join #578 and #579 into this PR

**Comment by diegolovison** [comment]
This PR contains files that were add in master a few days ago

**Comment by gustavolira** [comment]
Closing in favor of #596

**Pull request closed without merging**
