### PR TITLE
Testsuite fix

### PR DESCRIPTION
**Pull request by vjuranek**
* runs tests sequentially as when run in parallel they clash
* PowerMock doesn't work with abstract classes - convert `AbstractConfigurationTest` to normal class, however without `@Test` annotation so that it's not run by TestNG. Nicer solution can be done once switched to jUnit, which doesn't require test class to inherit from `PowerMockTestCase`

### CODE REVIEW

**Comment by rvansa** [comment]
@vjuranek what and why hangs when running them in parallel?

**Comment by vjuranek** [comment]
@rvansa 
what: random tests in `extensions/cache`, I tired now and it was `BackgroundStressorsGeneralTest`, waiting for checking the operations (in `BackgroundOpsManager.waitUntilChecked()`)

why: unfortunately no idea:-(

**Comment by jmarkos** [comment]
This makes the testsuite pass, so +1 from me. @rvansa unless you have further comments I'll integrate it.

**Comment by jmarkos** [comment]
Merged, thanks.

**Pull request closed without merging**
