### PR TITLE
Minor fixes for Docker benchmark

### PR DESCRIPTION
**Pull request by zhostasa**
* moved benchmark config to core to be picked up by build + some fixes
* documentation
* added config change to server.xml to support this benchmark

Also did some minor formatting changes to prevent jekyll glitches on site

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @zhostasa I am getting the following error when running the benchmark:

`13:43:48,636 INFO  [org.radargun.Slave] (sc-main) Service is DockerService {containerName=mod_cluster, dockerRegistry=registry.hub.docker.com, env=MODCLUSTER_ADVERTISE=Off
MODCLUSTER_MANAGER=127.0.0.1
MODCLUSTER_NET=127.0.0
, exposedPorts=80/tcp
6666/tcp
23364/udp
, image=karm/mod_cluster-master-dockerhub, password=, serverUri=unix:///var/run/docker.sock, username= }
13:43:49,488 INFO  [org.radargun.Slave] (sc-main) Starting stage ScenarioInit
13:43:49,518 INFO  [org.radargun.Slave] (sc-main) Finished stage ScenarioInit
13:43:49,521 INFO  [org.radargun.RemoteMasterConnection] (sc-main) Message successfully sent to the master
13:43:49,533 INFO  [org.radargun.Slave] (sc-main) Starting stage ServiceStart
13:43:49,534 INFO  [org.radargun.stages.lifecycle.ServiceStartStage] (sc-main) Startup staggering, this is the slave with index 0, not sleeping
13:43:49,535 INFO  [org.radargun.stages.lifecycle.ServiceStartStage] (sc-main) Ack master's StartCluster stage. Local address is: /127.0.0.1. This slave's index is: 0
13:43:49,665 ERROR [org.radargun.Slave] (sc-main) Unexpected error in scenario
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.radargun.config.InitHelper.processAnnotatedMethods(InitHelper.java:109) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.config.InitHelper.destroy(InitHelper.java:25) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:111) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158) [radargun-core-3.0.0-SNAPSHOT.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.radargun.config.InitHelper.processAnnotatedMethods(InitHelper.java:107) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	... 3 more
Caused by: java.lang.NullPointerException: Factory not initialized. You probably forgot to call init()!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228) ~[guava-19.0.jar:?]
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.close(NettyDockerCmdExecFactory.java:578) ~[docker-java-3.0.3.jar:?]
	at org.radargun.utils.Utils.close(Utils.java:602) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.service.DockerService.destroy(DockerService.java:211) ~[plugin-docker-3.0.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.radargun.config.InitHelper.processAnnotatedMethods(InitHelper.java:107) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	... 3 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.radargun.config.InitHelper.processAnnotatedMethods(InitHelper.java:109)
	at org.radargun.config.InitHelper.destroy(InitHelper.java:25)
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:111)
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:158)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.radargun.config.InitHelper.processAnnotatedMethods(InitHelper.java:107)
	... 3 more
Caused by: java.lang.NullPointerException: Factory not initialized. You probably forgot to call init()!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.close(NettyDockerCmdExecFactory.java:578)
	at org.radargun.utils.Utils.close(Utils.java:602)
	at org.radargun.service.DockerService.destroy(DockerService.java:211)
	... 8 more
`

I think you need a method with the `@Init` annotation in `DockerService`. It can just call `configureDockerClient()` instead of calling it from the `start()` method.

**Comment by zhostasa** [comment]
@alanfx do you have updated docker? I can't reproduce this

**Comment by alanfx** [comment]
@zhostasa OK, I finally got this working on Fedora. I am still getting the error above on MacOS. There are a couple of things that the doc needs to say as well:

1. I had to have read and write access to the `/var/run/docker.sock` file
2. `org.jboss.modcluster.container.catalina.standalone.ModClusterListener` is included with JWS, so you can't just use any old Tomcat version.

If you can make these changes, I'll merge and at least I know what to do to merge it if you don't!

Thanks

**Comment by zhostasa** [comment]
There you go

**Comment by alanfx** [comment]
@zhostasa ok, thanks. Merging

**Pull request merged**
