### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by zhostasa**
* Minor fix to stylesheet for 2nd level navbar tabs
* New Properties tab under General tab
* Minor improvements and fixes on Benchmark configuration tabs
* Added examples to Configurations and Scenario tabs

### CODE REVIEW

**Comment by zhostasa** [comment]
Please go ahead and fact-check this if you feel like it

**Comment by zhostasa** [comment]
Added minor tweaks and generators/selectors description

**Comment by mgencur** [comment]
Hi @zhostasa ,
this looks very good. I have found mostly small issues. Here they are:
* configurations.md

"Setup element attributes" ...could we have "setup" in bold and rest of the title in normal font. It was a little hard to understand whether it is a verb or noun
"Setup core elements" ...same here?

Not entirrely - Not entirely
First config -> The first config
second config -> The second config
This configuration take advantage -> This configuration takes advantage
infinispan -> Infinispan (several occurences)
uselful -> useful
hotrod -> HotRod
This configuration assumes only two servers -> This configuration assumes only two servers.

* key generators page

purposses -> purposes

* key generators, value generators, key selectors

I'm missing the enclosing tag, i.e. where is user supposed to place those tags?

* properties page

where can be expressions placed? a typical example please
"parsing na master " ????
experrion -> expression

* scenario page
Stage element attributes (shared) -> stage element attributes (shared)
runfor -> run for
place -> placed
to in order -> in order

**Comment by zhostasa** [comment]
Man, I feel like when my dad used to correct my writing 20 years ago, this is mildly embarrassing:-) Thanks 
The description for the placement of the generator/selector elements is above the example, but it was factually wrong, I rewrote it somewhat. 
I will have corrected version in today.

**Comment by mgencur** [comment]
Sorry about that. Maybe some kind of spellcheck would prevent these issues. But when I get to review a PR for docs I also look at correct spelling.

**Comment by zhostasa** [comment]
You have nothing to be sorry about I embarrassed myself, I did not mean to imply your fault there:-) Anyway, new and better version is up, have a looksie. I will look into some spellchecking options.

**Comment by mgencur** [comment]
Looks nice. Thanks!

**Pull request merged**
