### PR TITLE
Enable to configure backup clusters for HR client, 2.x

### PR DESCRIPTION
**Pull request by mcimbora**
- Add infinispan81 plugin
- Backport fix for ISPN server start script

### CODE REVIEW

**Comment by mcimbora** [comment]
rebased

**Comment by rvansa** [comment]
Looks OK, but GH tells me that there are conflicts.

**Comment by vjuranek** [comment]
@mcimbora could you please rebase, so that @rvansa can integrate it? @rvansa urge me to finish PR #318 and it depends on this PR. Thanks!

**Comment by mcimbora** [comment]
@vjuranek Rebased

**Comment by mcimbora** [comment]
@rvansa ^^

**Comment by rvansa** [comment]
Integrated, thanks.
@mcimbora In future pls set labels on PR as well.

**Pull request merged**
