### PR TITLE
gh-387 CPU and Memory usage charts for Master node

### PR DESCRIPTION
**Pull request by mgencur**

### CODE REVIEW

**Comment by jmarkos** [comment]
Isn't there some way to deduplicate the code? MasterMonitors and SlaveMonitors looks almost the same.

**Comment by mgencur** [comment]
There may be a way but that would include abstract classes and more complicated hierarchy. The current solution looked reasonable to me. Can you suggest something better?

**Comment by mgencur** [comment]
Actually, it was not too complicated. Here it is:)

**Comment by jmarkos** [comment]
Great, thanks! Integrated.

**Pull request closed without merging**
