### PR TITLE
Move existing wiki documents to GitHub pages

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by rvansa** [comment]
Feel free to push anything doc-like yourselves.

**Comment by rvansa** [comment]
Btw. I can't see anything on https://radargun.github.io/ so far

**Comment by mcimbora** [comment]
@rvansa Pushed, use the following link: https://radargun.github.io/radargun/.

**Comment by rvansa** [comment]
@mcimbora In that case, I would make this organizational pages, just to use simply http://radargun.github.io

**Comment by mcimbora** [comment]
@rvansa Done, sources are available at https://github.com/radargun/radargun.github.io

**Comment by rvansa** [comment]
@mcimbora great, can we remove gh-pages branch then?

**Comment by mcimbora** [comment]
Makes sense, done.

**Pull request merged**
