### PR TITLE
Renaming to remove the words Master and Slave from the codebase

### PR DESCRIPTION
**Pull request by alanfx**
All references to MASTER, Master, and master have been changed to MAIN, Main, and main.
All references to SLAVE, Slave, and slave have been changed to WORKER, Worker, and worker.

There are still references to Master related to the terminology in JGroups, Spark, and
OpenShift

### CODE REVIEW

**Comment by diegolovison** [comment]
@alanfx did you give a try with https://plugins.jenkins.io/radargun/ ?

**Comment by alanfx** [comment]
Hey @diegolovison, I did not, and I'll look through the source code now to see what changes will be needed. The website also needs to be changed, so maybe we'll keep these PRs open until everything is ready to go at once?

**Comment by diegolovison** [comment]
No problem. Hope to get those words out soon!

**Comment by diegolovison** [comment]
Merged. Thanks @alanfx

**Pull request merged**
