### PR TITLE
#275 Don't set expected num. of slaves if not explicitly set, default…

### PR DESCRIPTION
**Pull request by vjuranek**
… should be group size

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @vjuranek, I made this change to handle the issue you raised. IMO, you should set the expectNumSlaves to the correct value or the group size.

**Comment by vjuranek** [comment]
Groups size doesn't take any effect as it's taken into account only when `expectedSlaves` is not set (see [LifecycleHelper.java#L64](https://github.com/radargun/radargun/blob/master/core/src/main/java/org/radargun/stages/lifecycle/LifecycleHelper.java#L64)). 

In most of the cases IMHO the `expectedSlaves` is equal to the group size so using `null` as default (and therefore effectively using group size) seems to me more user friendly.

**Comment by alanfx** [comment]
I think the problem is with a benchmark that increases the number of services running on each iteration. In that case the group size is the wrong value for `expectedSlaves`. The other situation where this fails is when you specify multiple group names in the `groups` property.

**Comment by vjuranek** [comment]
OK, makes sense to me, thanks for explanation @alanfx ! Closing.

**Comment by alanfx** [comment]
Thanks, @vjuranek. I'm still not sure this is a `perfect` solution for this, but I don't know if that exists!

**Pull request closed without merging**
