### PR TITLE
Support bulk data loading

### PR DESCRIPTION
**Pull request by mcimbora**
Please do not integrate yet, the purpose of this PR is to get an early preview - i.e. wasn't refactored yet

As to batch + tx combo, currently one batch == one unit of transaction. We can discuss whether this should be changed to per key approach.

### CODE REVIEW

**Comment by rvansa** [comment]
@alanfx Actually the IGNORE_RETURN_VALUES should be used for all BasicOperations.Cache.put() calls - the version without this flag should be getAndPut(), according to JCache semantics. And putAll already returns void. But that should not be related to this PR, it's plugin implementation stuff.

**Comment by rvansa** [comment]
@mcimbora Two concerns: 
I) this will conflict with LoadDataStage -> LoadStage separation in my other PR (I assume you want this in 3.0 branch, too)
II) could loadEntry share the code more between bulk/non-bulk loaders? And it should be probably renamed, when it loads multiple entries...

**Comment by alanfx** [comment]
@rvansa so you are saying that the BasicOperations trait for Infinispan should do this? I don't see it in the code now, and it seems like it should be parameterized for the stages that do want to check the return value. Thanks for reviewing this PR as well. It's a little time-critical for a test next week.

**Comment by rvansa** [comment]
@alanfx Yes, there should be no custom flags, just the trait. InfinispanOperations.Cache uses ignoreReturnValueImpl for implementing the put() call, which has the flag set.

**Comment by alanfx** [comment]
@rvansa Thanks, I see it now

**Comment by rvansa** [comment]
@mcimbora Is this still preview?

**Comment by mcimbora** [comment]
@rvansa I'm working on refactoring the stage a bit & adding some tests. I'll let you know when I'm done (ongoing tasks with higher priority).

**Comment by mcimbora** [comment]
@rvansa Updated

**Comment by rvansa** [comment]
Integrated, thanks.

**Pull request closed without merging**
